backend:
  name: github
  repo: brunodeangelis/tolkienletters
  branch: content
  squash_merges: true

publish_mode: editorial_workflow
# local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "letters"
    label: "Letters"
    label_singular: "Letter"
    identifier_field: "number"
    folder: "content/letters"
    format: "frontmatter"
    create: true
    editor:
      preview: false
    summary: "Letter {{slug}} - To {{fields.recipient}}"
    fields:
      - { name: "title", label: "Title", widget: "string", hint: "For example: To Edith Bratt" }
      - { name: "number", label: "Number", widget: "number", min: 1, max: 700 }
      - name: "date_fields"
        label: "Date"
        widget: "object"
        fields:
          - {
              name: "date",
              label: "Date",
              widget: "datetime",
              date_format: true,
              time_format: false,
              picker_utc: false,
            }
          - {
              name: "unknown_day",
              label: "Unknown day",
              widget: "boolean",
              required: false,
              hint: "On some letters, the day is unknown",
            }
          - {
              name: "unknown_month",
              label: "Unknown month",
              widget: "boolean",
              required: false,
              hint: "On some letters, the month is unknown",
            }
      - { name: "address", label: "Address", widget: "string" }
      - { name: "recipient", label: "Recipient", widget: "string" }
      - {
          name: "context",
          label: "Context",
          widget: "text",
          hint: "On some letters, there is some text that gives context to what the letter is about",
        }
      - { name: "body", label: "Body", widget: "markdown" }
    sortable_fields: ["date_fields.date", "number", "recipient"]
